config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get '/login' => 'login#login', :as => :login
  get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
  get '/login/github', to: redirect('auth/github'), as: :github_login
  get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
  get '/auth/github/callback', to: 'login#github', as: :github_callback
  get '/logout' => 'login#logout', :as => :logout
  get '/user/profile', to: 'user#profile', as: :user_profile

  root to: 'map#index', as: 'root'
  get '/state/:state_symbol' => 'map#state', :as => :state_map
  get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

  get '/ajax/state/:state_symbol' => 'ajax#counties'

  # Routes for Events
  resources :events, only: %i[index show]
  get '/my_events/new' => 'my_events#new', :as => :new_my_event
  post '/my_events/new', to: 'my_events#create'
  get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
  match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
  delete '/my_events/:id', to: 'my_events#destroy'

  # Routes for Representatives
  resources :representatives, only: [:index]
  resources :representatives do
    resources :news_items, only: %i[index show]
    get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
        :as                                                    => :new_my_news_item
    post '/representatives/:representative_id/my_news_item/new', to: 'my_news_items#create'
    get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
        :as                                                    => :edit_my_news_item
    match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                  via: %i[put patch]
    delete '/representatives/:representative_id/my_news_item/:id', to: 'my_news_items#destroy'
  end
  get '/search/(:address)' => 'search#search', :as => 'search_representatives'
end

app/models/representative.rb
# frozen_string_literal: true

#------------------------------------------------------------------------------
# Representative
#
# Name       SQL Type             Null    Primary Default
# ---------- -------------------- ------- ------- ----------
# id         INTEGER              false   true
# name       varchar              true    false
# created_at datetime             false   false
# updated_at datetime             false   false
# ocdid      varchar              true    false
# title      varchar              true    false
#
#------------------------------------------------------------------------------

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all

  def self.civic_api_to_representative_params(rep_info)
    reps = []

    rep_info.officials.each_with_index do |official, index|
      ocdid_temp = ''
      title_temp = ''

      rep_info.offices.each do |office|
        if office.official_indices.include?(index)
          title_temp = office.name
          ocdid_temp = office.division_id
        end
      end

      rep = Representative.create!({ name: official.name, ocdid: ocdid_temp,
          title: title_temp })
      reps.push(rep)
    end

    reps
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
  .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
    %h1.text-center Search for a Representative

  .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
    = form_tag search_representatives_path, method: :get do
      .form-group.row
        .col-md-4
          %label.col-form-label
            Enter a location:
        .col-md-6
          = text_field_tag(:address, nil, class: 'form-control')

      .actions
        = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
  .row
    .col-md-8.offset-md-2
      .table-responsive-md.pt-5
        %table.table.table-striped.table-hover#events
          %caption Table of Representatives
          %thead.thead-dark
            %tr
              %th Name
              %th Office
              %th Links
          %tbody
            - @representatives.each_with_index do |rep, _index|
              %tr
                %td= rep.name
                %td= rep.title
                %td
                  = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                    %i.fas.fa-newspaper
                    News Articles